language: java
jdk:
- oraclejdk8
script:
- mvn clean install
notifications:
  slack:
    secure: g+R7mtDPvXEZU9mR3iAC25N2GzfIWsK4bgB7GtE6cAco8+U1WHzj46i2XZoTqoBYpcfXlt9e9FmjsXKVxCwcUWij9ZA2qCmNXpVbU3HOle7lJgHgFEyGgtOV7kqylHssMGBuZV4nNGZz/c7kR9EUw6V8kYQnAggX2ziM1n2xurAV6NyzqIobpKzcFvbAlOVV3LnfX4cBiFPcpvgPWF0g/dal7RxQtkRJRQnn1xyBbxCtZ9rivko0GKDEltLUBhVLPiWdVB1wZUexSdgARPjxEhujjlzL0bteKsCe/z0a3dsGonKwuUWHyrS8UpIxyYsOoLC6iRT/DWahkt6n4zXxo4QbY7kqESFT5RUxDQuzKyEPoSXeAv+UzaV4iXEZejcq28k24hMn9iPnWo6NMv0DlgPzw8ZPjBL7TgnaXAEvDARs5T4yYrVfmga4EadunVKLHU27NhJfgw+Z1dAQTvymmSXTkhIjFUxFtEXfzjQdt6EhgQqZq8r8FfVToMdE09vMlR27zYp1FrKwb1jH9Efrto4DTm9OxzFvfzXb+e0szyOTx4tdiItjkJyF6fNiw8KUoIcWMfrq7z9Xdfx7VtGRP/f3UWj901iqQ90NvMxaS1ZH1/KtsJirdE7rieXIb4O3PWb3MrRT/BPNkd6ZBqxOGMXB3eiT3Sla+g9JxZ7h1SM=
  email: false